### ISSUE TITLE
Optimality

### ISSUE THREAD

**Issue by amkrajewski** [hamidb80/maze-vis#1]
Hi @hamidb80, very cool demonstrator / visualization tool! I ran a couple of quick tests on the large grid, and the A* often gives suboptimal results in terms of the number of steps (what gets printed). Perhaps that is because of the distance metric used? Best of luck!

**Comment by hamidb80** [comment]
Hey Adam!

Here's my investigations:
1. calculating cost is wrong:
https://github.com/hamidb80/maze-vis/commit/8d879a750b87a0506183b0faad77d20340d2ca85#diff-063743a229cdcda2bdc21829cc625a292f74c7615bf1033b002343969296d334L271

2. the distance metric was **Euclidean distance** [as you mentioned], I've replaced it with **Manhattan distance**.

-------------

Thanks a lot for noticing the problem.
